spring:
    datasource:
        driverClassName: org.postgresql.Driver
        password: password
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        show-sql: true
security:
  user:
    password: p


#facebook:
#  client:
#    clientId: 579641695554740
#    clientSecret: 8aab19c71f2e73b158a389904b0ceb5b
#    accessTokenUri: https://graph.facebook.com/oauth/access_token
#    userAuthorizationUri: https://www.facebook.com/dialog/oauth
#    tokenName: oauth_token
#    authenticationScheme: query
#    clientAuthenticationScheme: form
#  resource:
#    userInfoUri: https://graph.facebook.com/me